server:
  port: ${PORT:8093}

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}/${POSTGRES_DATABASE:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
  aop:
    auto: true
    proxy-target-class: true

instrumentation:
  name: heloc-profile-service
  version: 1.0
  environment: DEV
  remote-address-header: X-Forwarded-For
  user-header: X-USER
  enabled: true
  instance-id: 11
  start-time: 14-Mar-2026
  ignore-duration-in-millis: 20
  handlers:
    log:
      layers:
      - FILTER
      - CONTROLLER
      - SERVICE
      - REPOSITORY
      event-names: all
      ignore-parameters: false
      ignore-outcome: true
      ignore-exception-stack: false
      limited: false
    new-relic:
      event-names: none
    aws-sns:
      event-names: sourcing
    tracing:
      event-names: tracing
      metrics:
      - NAME
      - VERSION
      - INSTANCE_ID
      - TRACE_ID
      - ENVIRONMENT
      - CORRELATION_ID
      - USER_ID
      - LOCAL_ADDRESS
      - REMOTE_ADDRESS
      - URI

rest:
  impl-class: me.anichakra.poc.pilot.framework.instrumentation.impl.RestTemplateImpl
  consumers:
    - name: prove-verify
      url: ${PROVE_API_URL:http://localhost:9090/prove/verify}
      secured: false
      contentType: application/json
      responseType: me.anichakra.poc.pilot.heloc.profile.domain.BorrowerProfile
      method: POST
